### ISSUE TITLE
Logging in with Facebook Issue

### ISSUE THREAD

**Issue by jaruesink** [jaruesink/coop#9]
Steps to Reproduce:
Step 1: (click the red G button to logout of FB)
Step 2: (click the blue F button to login to FB)
Step 3: notice the following screen
![screen shot 2016-03-06 at 2 10 02 pm](https://cloud.githubusercontent.com/assets/4207065/13556664/5a8c4202-e3a5-11e5-8439-9371f5a72922.png)
Step 4: figure out why it isn't applying the data to the view

**Comment by jamrizzi** [comment]
Fixed in #11

**Comment by jaruesink** [comment]
This happens with autofilling data into the create account also. it only does this if you're not already logged into Facebook. is there a way to run something like $apply in Angular 1, maybe something with Zone.js?

**Comment by jaruesink** [comment]
This probably has to do with the asynchronous Facebook calls. Is there a way to make them not asynchronous?

**Comment by jaruesink** [comment]
related to #15, apparently making asynchronous calls is a bad idea.

**Comment by jaruesink** [comment]
related to #15, apparently making asynchronous calls synchronous is a bad idea
